NewAppearances/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Forward a url with no resource specified or the home resource specified to the home application
    url(r'^(home/)?$', include('home.urls')),
    # Forward a url with the contact/ resource to the services application
    url(r'^contact/', include('contact.urls')),
    # Forward a url with the hours/ resource to the hours application
    url(r'^hours/', include('hours.urls')),
    # Forward a url with the directions/ resource to the directions application
    url(r'^directions/', include('directions.urls')),
    # Forward a url with the products/ resource to the products application
    url(r'^products/', include('products.urls')),
    # Forward a url with the services/ resource to the services application
    url(r'^services/', include('services.urls')),
    # Forward a url with admin/docs/ to the admin documentation url
    url(r'^admin/docs/', include('django.contrib.admindocs.urls')),
    # Forward a url with admin/ to the admin site url
    url(r'^admin/', include(admin.site.urls)),
    # To include the image repo
    url(r'^images/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
)

home/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    # If no resource is specified call the views.py home function
    url(r'^$', views.home, name='home'),
)

hours/urls.py
from django.conf.urls import patterns, url

from . import views

urlpatterns = patterns('',
    # If no resource is specified call the views.py hours function
    url(r'^$', views.hours, name='hours'),
)

hours/models.py
from django.db import models


class Day(models.Model):
    """
    Open hours for days of the week
    """
    # Constants for days of the week
    MONDAY = 1
    TUESDAY = 2
    WEDNESDAY = 3
    THURSDAY = 4
    FRIDAY = 5
    SATURDAY = 6
    SUNDAY = 7

    # Choices to map day constants to Names
    day_choices = (
        (MONDAY, "Monday"),
        (TUESDAY, "Tuesday"),
        (WEDNESDAY, "Wednesday"),
        (THURSDAY, "Thursday"),
        (FRIDAY, "Friday"),
        (SATURDAY, "Saturday"),
        (SUNDAY, "Sunday"),
    )

    day_name = models.IntegerField(choices=day_choices, unique=True, help_text="Name of the day of the week")
    start_time = models.CharField(blank=True, max_length=7, help_text="Time the shop opens")
    end_time = models.CharField(blank=True, max_length=7, help_text="Time the shop closes")

    def get_hours_range(self):
        """
        Get the hours to display for a given day - Either closed or a <start>-<end> format
        """
        if self.start_time == '' and self.end_time == '':
            return "Closed"
        # TODO Make this a real error case
        elif self.start_time == '' or self.end_time == '':
            return "Somethings Wrong"
        else:
            return self.start_time + "-" + self.end_time

hours/views.py
from django.shortcuts import render

from .models import Day


def hours(request):
    """
    Display the hours for every day of the week

    **Context**

    ``hoursList``
    All of the days of the week and their corresponding times from :model:`hours.Day`

    **Templates**

    :template:`hours/hours.html`

    :param request Data sent to the sever as part of a web request
    :return A rendered hours file
    """
    return render(request, "hours/hours.html", {'hoursList': Day.objects.order_by('day_name')},)

hours/templates/hours/hours.html
{%  extends "base/base.html" %}

{% load staticfiles %}

{% block appStylesheet %}
    <link rel ="stylesheet" type="text/css" href="{% static "hours/style/hours.css" %}" />
{% endblock %}

{% block body %}
    <div class="hoursHeader">
        <h1>Hours of Operation</h1>
    </div>
    <div class="hoursContainer">
        <!--Print day of week and hours in a row and change class every other row for styling-->
        {% for day in hoursList %}
            {% if forloop.counter|divisibleby:2 %}
                <div class="even">
            {% else %}
                <div class="odd">
            {% endif %}
                    <p class="dayOfWeek">{{ day.get_day_name_display }}</p>
                    <p class="hoursForDay">{{ day.get_hours_range }}</p>
                </div>
        {% endfor %}
    </div>
    <div class="hoursFooter">
        <h3>Contact us for the hours of individual stylists</h3>
    </div>
{% endblock %}